name = "pb"
type = "javascript"

workers_dev = true
webpack_config = "webpack.config.js"

kv_namespaces = [
  { binding = "PB", id = "abab31d6e30143eda25bc6a072318424", preview_id = "abab31d6e30143eda25bc6a072318424" },
]

[build]
command = "yarn install && yarn build"

[build.upload]
format = "service-worker"
