name = "pb"
compatibility_date = "2023-01-28"

workers_dev = true
main = "src/index.js"

# config for default production environment
vars = { ENVIRONMENT = "production" }
# route = { pattern = "shz.al", custom_domain = true }
kv_namespaces = [
  { binding = "PB", id = "abab31d6e30143eda25bc6a072318424" },
]

[env.preview]
vars = { ENVIRONMENT = "preview" }
# route = { pattern = "pb-preview.shz.al", custom_domain = true }
minify = false

kv_namespaces = [
  { binding = "PB", id = "f56ae0043abd4bb4ab61c52071bd9c7f" }
]

